title: NEST
description: Netplay Event Starter Tools
url: "https://enpicie.github.io"
baseurl: "/nest"
github_url: "https://github.com/enpicie/nest"

# Tell Jekyll where the source lives
source: .

# Don't process these
exclude:
  - index.html
  - _site/
  - .jekyll-cache/
  - README.md
